name: CI/CD

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

permissions:
  contents: read

jobs:
  CI-CD:
    runs-on: ubuntu-latest
    steps:

      ## jdk setting
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      ## gradle caching
      - name: Gradle Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      ## gradle build
      - name: Build with Gradle
        run: ./gradlew clean build

      ## docker build & push to dockerhub
      - name: Docker build & push to dockerhub
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t ${{ secrets.DOCKER_REPO }}/shorturl .
          docker push ${{ secrets.DOCKER_REPO }}/shorturl

      ## deploy to ec2
      - name: Deploy to ec2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_ENDPOINT }}
          username: ${{ secrets.EC2_USERNAME }}
          passwrod: ${{ secrets.EC2_PASSWORD }}
          port: 22
          script: |
            sudo docker remove -f $(docker ps -qa)
            sudo docker pull ${{ secrets.DOCKER_REPO }}/shorturl
            docker-compose up -d
            docker image prune -f