name: test-every-pull-request

on:
  pull_request:
    branches:
      - develop
      - main

permissions:
  contents: read

jobs:
  test:
    name: Test lint, tsc, build

    runs-on: ubuntu-latest

    steps:
      ## jdk setting
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      ## gradle build
      - name: Build with Gradle
        run: ./gradlew clean build